name: Build

on:
    workflow_dispatch:
        inputs:
          tag:
            description: 'Tag Name'
            required: true
          prerelease:
            description: 'Prerelease'
            type: boolean
            default: false

jobs:
    build-mac:
        runs-on: macos-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: 20
            - name: Install
              run: npm install
            - name: Setup Certificate
              run: |
                sudo security add-trusted-cert -d -r trustAsRoot -k /Library/Keychains/System.keychain dist/sign.cer
            - name: Build
              run: npm run build
            - name: Rename
              run: |
                cp dist/eaglergrab-1.0.0-arm64.dmg dist/release-mac.dmg
            - name: Upload
              uses: actions/upload-artifact@v3
              with:
                  name: release-mac.dmg
                  path: dist/release-mac.dmg
    build-win:
        runs-on: windows-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: 20
            - name: Install
              run: npm install
            - name: Build
              run: npm run build
            - name: Rename
              run: |
                cp "dist/eaglergrab Setup 1.0.0.exe" dist/setup-win.exe
            - name: Upload
              uses: actions/upload-artifact@v3
              with:
                name: setup-win.exe
                path: dist/setup-win.exe
    build-linux:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: 20
            - name: Install
              run: npm install
            - name: Build
              run: npm run build
            - name: Rename
              run: |
                cp dist/eaglergrab-1.0.0.AppImage dist/release-linux.AppImage
            - name: Upload
              uses: actions/upload-artifact@v3
              with:
                name: release-linux.AppImage
                path: dist/release-linux.AppImage
    release:
        runs-on: ubuntu-latest
        needs: [build-mac, build-win, build-linux]
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Download Mac
              uses: actions/download-artifact@v3
              with:
                  name: release-mac.dmg
                  path: dist
            - name: Download Windows
              uses: actions/download-artifact@v3
              with:
                  name: setup-win.exe
                  path: dist
            - name: Download Linux
              uses: actions/download-artifact@v3
              with:
                  name: release-linux.AppImage
                  path: dist
            - name: Release
              uses: softprops/action-gh-release@v2
              with:
                  files: |
                    dist/release-mac.dmg
                    dist/setup-win.exe
                    dist/release-linux.AppImage
                  prerelease: ${{ github.event.inputs.prerelease }}
                  generate_release_notes: true
                  tag_name: ${{ github.event.inputs.tag }}
                  name: ${{ github.event.inputs.tag }}