name: Build

on:
    push:
        branches:
            - main

jobs:
    build-mac:
        runs-on: macos-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: 16
            - name: Install
              run: npm install
            - name: Build
              run: npm run build
            - name: Rename
              run: |
                cp dist/eaglergrab-1.0.0-arm64.dmg dist/release-mac.dmg
            - name: Upload
              uses: actions/upload-artifact@v3
              with:
                  name: release-mac.dmg
                  path: dist/release-mac.dmg
    build-win:
        runs-on: windows-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: 16
            - name: Install
              run: npm install
            - name: Build
              run: npm run build
            - name: Rename
              run: |
                ls
    build-linux:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: 16
            - name: Install
              run: npm install
            - name: Build
              run: npm run build
            - name: Rename
              run: |
                ls
